name: Static site build

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Fetch data']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Get build date
        id: date-get
        run: |
          echo "BUILD_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Print build date
        id: date-print
        run: |
          echo ${{ env.BUILD_DATE }} >> .last-updated
      - name: Build
        run: |
          npm ci
          npm run build
          touch dist/.nojekyll
          echo "312.show" >> dist/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: dist
